# Generated by Django 4.2.5 on 2023-09-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='was_returned',
            field=models.BooleanField(default=False),
        ),
    ]
